In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('training_data.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10738 entries, 0 to 10737
Data columns (total 12 columns):
customer_id                         10738 non-null object
customer_visit_score                10738 non-null float64
customer_product_search_score       10696 non-null float64
customer_ctr_score                  10738 non-null float64
customer_stay_score                 10701 non-null float64
customer_frequency_score            10738 non-null float64
customer_product_variation_score    10692 non-null float64
customer_order_score                10672 non-null float64
customer_affinity_score             10738 non-null float64
customer_active_segment             10715 non-null object
X1                                  10701 non-null object
customer_category                   10738 non-null int64
dtypes: float64(8), int64(1), object(3)
memory usage: 1006.8+ KB

In [4]:
data.head()

,customer_id,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1,customer_category
0,csid_1,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,C,F,0
1,csid_2,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,C,A,0
2,csid_3,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,C,BA,0
3,csid_4,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,AA,F,0
4,csid_5,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,C,AA,0

In [5]:
data.describe()

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_category
count,10738.000000,10696.000000,10738.000000,10701.000000,10738.000000,10692.000000,10672.000000,10738.000000,10738.000000
mean,19.060941,5.274847,0.175912,0.374230,2.376895,5.788180,3.150071,17.061836,0.120600
std,7.419609,1.882559,0.372829,1.222031,5.601911,2.531309,1.035416,18.762693,0.325677
min,0.568965,-0.161940,-0.547989,-0.462494,0.028575,2.752836,0.363338,-0.486834,0.000000
25%,13.518021,3.971587,0.010840,-0.027666,0.313610,4.193234,2.454017,4.530085,0.000000
50%,18.774109,5.218479,0.074078,0.037201,0.516830,4.842575,3.118394,12.653357,0.000000
75%,24.501719,6.520364,0.159606,0.179029,1.125380,6.286400,3.756566,23.114577,0.000000
max,47.306691,16.638243,2.679474,14.701914,52.395014,18.743836,9.090206,248.552755,1.000000

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
dependent_var=data['customer_category']
customer_active_seg, X1 =[],[]
customer_active_seg=encoder.fit_transform(data.iloc[:,9].fillna('Nan'))
X1=encoder.fit_transform(data.iloc[:,10].fillna('Nan'))
encoded_df=data.drop(['customer_id','customer_active_segment','X1','customer_category'],axis=1)
encoded_df=encoded_df.fillna(0.0)
encoded_df['customer_active_segment']=customer_active_seg
encoded_df['X1']=X1

encoded_df.head()

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
0,13.168425,9.447662,-0.070203,-0.139541,0.436956,4.705761,2.537985,7.959503,3,4
1,17.092979,7.329056,0.153298,-0.102726,0.380340,4.205138,4.193444,17.517381,3,0
2,17.505334,5.143676,0.106709,0.262834,0.417648,4.479070,3.878971,12.595155,3,2
3,31.423381,4.917740,-0.020226,-0.100526,0.778130,5.055535,2.708940,4.795073,1,4
4,11.909502,4.237073,0.187178,0.172891,0.162067,3.445247,3.677360,56.636326,3,1

In [7]:
encoded_df.describe()

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
count,10738.000000,10738.000000,10738.000000,10738.000000,10738.000000,10738.000000,10738.000000,10738.000000,10738.000000,10738.000000
mean,19.060941,5.254215,0.175912,0.372941,2.376895,5.763384,3.130709,17.061836,2.448687,1.861240
std,7.419609,1.907506,0.372829,1.220121,5.601911,2.554016,1.061186,18.762693,0.817422,1.358838
min,0.568965,-0.161940,-0.547989,-0.462494,0.028575,0.000000,0.000000,-0.486834,0.000000,0.000000
25%,13.518021,3.954833,0.010840,-0.027413,0.313610,4.183216,2.440469,4.530085,2.000000,1.000000
50%,18.774109,5.208070,0.074078,0.036739,0.516830,4.836307,3.110894,12.653357,3.000000,2.000000
75%,24.501719,6.513742,0.159606,0.178511,1.125380,6.274623,3.751178,23.114577,3.000000,2.000000
max,47.306691,16.638243,2.679474,14.701914,52.395014,18.743836,9.090206,248.552755,5.000000,5.000000

In [8]:
train_len=int(.8*(encoded_df.shape[0]))
train_x,train_y=encoded_df[:train_len],dependent_var[:train_len]
test_x,test_y=encoded_df[train_len:],dependent_var[train_len:]

In [9]:
from sklearn.ensemble import RandomForestClassifier

rfclf=RandomForestClassifier(random_state=0)

rfclf.fit(train_x,train_y)

print(f'training accuracyis:{rfclf.score(train_x,train_y)}')

pred4=rfclf.predict(test_x)

print(f'test accuracyis:{sk.metrics.accuracy_score(test_y,pred4)}')

training accuracyis:0.99988358556461
test accuracyis:0.9813780260707635

In [10]:
sub_data=pd.read_csv('testing_data.csv')
sub_data2=sub_data.set_index('customer_id')
sub_data2[0:5]

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
customer_id,,,,,,,,,,
csid_10739,22.500174,3.702145,0.118811,0.093253,0.689237,5.786842,3.748009,7.661716,B,BA
csid_10740,13.225950,3.600102,0.130985,0.053575,0.142756,3.940359,3.469659,33.999679,B,AA
csid_10741,14.603376,5.084047,-0.004651,-0.036299,0.333709,4.254662,3.855939,33.485630,B,AA
csid_10742,26.149905,3.025501,0.229740,0.204591,3.768405,6.942625,2.362421,0.795372,B,BA
csid_10743,19.810630,5.020400,-0.011347,-0.028780,0.286841,4.585513,3.278624,15.052058,C,BA

In [11]:
sub_customer_active_seg, sub_X1 =[],[]
sub_customer_active_seg=encoder.fit_transform(sub_data2.iloc[:,8].fillna('Nan'))
sub_X1=encoder.fit_transform(sub_data2.iloc[:,9].fillna('Nan'))
sub_encoded_df=sub_data2.drop(['customer_active_segment','X1'],axis=1)
sub_encoded_df=sub_encoded_df.fillna(0.0)
sub_encoded_df['customer_active_segment']=sub_customer_active_seg
sub_encoded_df['X1']=sub_X1

sub_encoded_df.head()

,customer_visit_score,customer_product_search_score,customer_ctr_score,customer_stay_score,customer_frequency_score,customer_product_variation_score,customer_order_score,customer_affinity_score,customer_active_segment,X1
customer_id,,,,,,,,,,
csid_10739,22.500174,3.702145,0.118811,0.093253,0.689237,5.786842,3.748009,7.661716,2,2
csid_10740,13.225950,3.600102,0.130985,0.053575,0.142756,3.940359,3.469659,33.999679,2,1
csid_10741,14.603376,5.084047,-0.004651,-0.036299,0.333709,4.254662,3.855939,33.485630,2,1
csid_10742,26.149905,3.025501,0.229740,0.204591,3.768405,6.942625,2.362421,0.795372,2,2
csid_10743,19.810630,5.020400,-0.011347,-0.028780,0.286841,4.585513,3.278624,15.052058,3,2

In [12]:
sub_customer_category=rfclf.predict(sub_encoded_df)

In [13]:
ans=pd.DataFrame({'customer_id':sub_encoded_df.index,
                  'customer_category':sub_customer_category})
ans.to_csv('solution.csv',index=False)